import { toast } from 'sonner'

export const notify = {
  loginSuccess: (name?: string) => toast.success(`Welcome back, ${name || 'Student'}!`),
  loginError: (msg?: string) => toast.error(msg || 'Login failed. Please check your credentials.'),
  resetPasswordEmailSent: () => toast.success('Password reset link sent! Check your email.'),
  registerSuccess: () => toast.success('Account created successfully! Please check your email.'),
  registerError: (msg?: string) => toast.error(msg || 'Registration failed. Please try again.'),
  logoutSuccess: () => toast.success('Logged out successfully!'),

  enrollSuccess: (courseName?: string) => toast.success(`Successfully enrolled${courseName ? ` in ${courseName}` : ''}!`),
  enrollError: (msg?: string) => toast.error(msg || 'Enrollment failed. Please try again.'),
  paymentSuccess: () => toast.success('Payment successful! You now have access to the course.'),
  paymentError: (msg?: string) => toast.error(msg || 'Payment failed. Please try again.'),
  paymentCancelled: () => toast.info('Payment cancelled.'),
  paymentRedirecting: () => toast.info('Redirecting to payment...'),

  lessonComplete: (title?: string) => toast.success(`Lesson completed${title ? `: ${title}` : ''}`),
  quizSubmitted: (score?: number) => toast.success(`Quiz submitted! Score: ${score}%`),
  quizFailed: () => toast.error('Quiz not passed. Please try again.'),
  noteSaved: () => toast.success('Notes saved!'),
  progressSaved: () => toast.success('Progress saved!'),

  certificateDownloaded: () => toast.success('Certificate downloaded!'),
  certificatesIssued: (count: number) => toast.success(`${count} certificate${count !== 1 ? 's' : ''} issued!`),
  certificateError: () => toast.error('Failed to download certificate.'),

  courseCreated: () => toast.success('Course created successfully!'),
  courseUpdated: () => toast.success('Course updated!'),
  courseDeleted: () => toast.success('Course deleted.'),
  moduleCreated: () => toast.success('Module created!'),
  moduleUpdated: () => toast.success('Module updated!'),
  moduleDeleted: () => toast.success('Module deleted.'),
  lessonCreated: () => toast.success('Lesson created!'),
  lessonUpdated: () => toast.success('Lesson updated!'),
  lessonDeleted: () => toast.success('Lesson deleted.'),
  testCreated: () => toast.success('Test created!'),
  testUpdated: () => toast.success('Test updated!'),
  testDeleted: () => toast.success('Test deleted.'),
  videoUploaded: () => toast.success('Video uploaded successfully!'),
  employeeAdded: () => toast.success('Employee added!'),
  employeeUpdated: () => toast.success('Employee updated!'),
  employeeDeleted: () => toast.success('Employee deleted.'),
  settingsSaved: () => toast.success('Settings saved!'),
  statusToggled: (active: boolean) => toast.success(`Status changed to ${active ? 'active' : 'inactive'}.`),

  studentAdded: () => toast.success('Student added!'),
  studentUpdated: () => toast.success('Student updated!'),
  studentDeleted: () => toast.success('Student deleted.'),
  studentsImported: (count: number) => toast.success(`${count} student${count !== 1 ? 's' : ''} imported!`),
  studentsAssignedToBatch: (count: number) => toast.success(`${count} student${count !== 1 ? 's' : ''} assigned to batch!`),
  studentsDeleted: (count: number) => toast.success(`${count} student${count !== 1 ? 's' : ''} deleted!`),

  batchCreated: () => toast.success('Batch created!'),
  batchUpdated: () => toast.success('Batch updated!'),
  batchDeleted: () => toast.success('Batch deleted.'),
  batchStudentsLoaded: () => toast.success('Batch students loaded.'),

  networkError: () => toast.error('Network error. Please check your connection.'),
  serverError: () => toast.error('Server error. Please try again later.'),
  unauthorized: () => toast.error('Please login to continue.'),
  sessionExpired: () => toast.warning('Session expired. Please login again.'),
  genericError: (msg?: string) => toast.error(msg || 'Something went wrong. Please try again.'),

  testimonialCreated: () => toast.success('Testimonial created!'),
  testimonialUpdated: () => toast.success('Testimonial updated!'),
  testimonialDeleted: () => toast.success('Testimonial deleted.'),

  comingSoon: () => toast.info('Coming soon!'),
  copied: () => toast.success('Copied to clipboard!'),
}
